version: "3.0"

services:

    php_apache:
        build: ./docker/php_apache/
        container_name: notfound_phpapache
        ports:
            - 80:80
        volumes:
            - "${PROJECT_ROOT}:/var/www"
        networks:
            - server

networks:
    server:
